### PR TITLE
Fix usage with JuMP v1.2

### LINKED ISSUE #204: Fix support for JuMP v1.2
## Version info
```
julia> versioninfo()
Julia Version 1.8.0
Commit 5544a0fab7 (2022-08-17 13:38 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 12 × Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 6 on 12 virtual cores
Environment:
  JULIA_NUM_THREADS = 6
  JULIA_PKG_SERVER = https://mirrors.tuna.tsinghua.edu.cn/julia
  JULIA_EDITOR = code
```
On julia 1.8.0, Alpine.jl failed to precompile.
I have: ` [4076af6c] JuMP v1.2.0`
## Error message
```
julia> import Pkg; Pkg.precompile()
Precompiling project...
  ✗ Alpine
  0 dependencies successfully precompiled in 9 seconds. 341 already precompiled.

ERROR: The following 1 direct dependency failed to precompile:

Alpine [07493b3f-dabb-5b16-a503-4139292d7dd4]

Failed to precompile Alpine [07493b3f-dabb-5b16-a503-4139292d7dd4] to C:\Users\dell\.julia\compiled\v1.8\Alpine\jl_A8E2.tmp.
ERROR: LoadError: TypeError: in Union, expected Type, got a value of type typeof(JuMP.NLPEvaluator)
Stacktrace:
 [1] top-level scope
   @ C:\Users\dell\.julia\packages\Alpine\Pn6vZ\src\MOI_wrapper\MOI_wrapper.jl:6
 [2] include(mod::Module, _path::String)
   @ Base .\Base.jl:419
 [3] include(x::String)
   @ Alpine C:\Users\dell\.julia\packages\Alpine\Pn6vZ\src\Alpine.jl:3
 [4] top-level scope
   @ C:\Users\dell\.julia\packages\Alpine\Pn6vZ\src\Alpine.jl:19
 [5] include
   @ .\Base.jl:419 [inlined]
 [6] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
   @ Base .\loading.jl:1554
 [7] top-level scope
   @ stdin:1
in expression starting at C:\Users\dell\.julia\packages\Alpine\Pn6vZ\src\MOI_wrapper\MOI_wrapper.jl:6
in expression starting at C:\Users\dell\.julia\packages\Alpine\Pn6vZ\src\Alpine.jl:3
in expression starting at stdin:1
Stacktrace:
 [1] pkgerror(msg::String)
   @ Pkg.Types C:\Users\dell\.julia\juliaup\julia-1.8.0+0.x64\share\julia\stdlib\v1.8\Pkg\src\Types.jl:67
 [2] precompile(ctx::Pkg.Types.Context, pkgs::Vector{String}; internal_call::Bool, strict::Bool, warn_loaded::Bool, already_instantiated::Bool, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Pkg.API C:\Users\dell\.julia\juliaup\julia-1.8.0+0.x64\share\julia\stdlib\v1.8\Pkg\src\API.jl:1427
 [3] precompile
   @ C:\Users\dell\.julia\juliaup\julia-1.8.0+0.x64\share\julia\stdlib\v1.8\Pkg\src\API.jl:1058 [inlined]
 [4] #precompile#225
   @ C:\Users\dell\.julia\juliaup\julia-1.8.0+0.x64\share\julia\stdlib\v1.8\Pkg\src\API.jl:1057 [inlined]
 [5] precompile (repeats 2 times)
   @ C:\Users\dell\.julia\juliaup\julia-1.8.0+0.x64\share\julia\stdlib\v1.8\Pkg\src\API.jl:1057 [inlined]
 [6] top-level scope
   @ REPL[3]:1
```

### PR DESCRIPTION
**Pull request by odow**
Potentially closes #204 

Trying some other things locally as well.

### CODE REVIEW

**Comment by odow** [comment]
I guess I missed this package in my search for things that JuMP v1.2 broke. There's a bunch of internal function usage:

https://github.com/lanl-ansi/Alpine.jl/blob/fc377e6b9f1a54c9b8494e47f8472a326e6416ee/test/test_solver.jl#L306

**Comment by harshangrjn** [comment]
> _create_nlp_block_data

This internal function usage was mainly taken from https://github.com/lanl-ansi/Alpine.jl/blob/fc377e6b9f1a54c9b8494e47f8472a326e6416ee/test/runtests.jl#L22

**Comment by odow** [comment]
Yeah, my work-around is to set an optimize hook so JuMP can setup everything internally, but we don't actually hit `optimize!`.

**Comment by odow** [comment]
@harshangrjn take a look. This should be good to go now.

**Comment by harshangrjn** [comment]
Thanks @odow

**Pull request merged**
