### PR TITLE
OBBT issue fixes

### PR DESCRIPTION
**Pull request by fatihcengil**
- Fixed OBBT average reduction issue 
- Fixed bug in `best_rel_gap ` evaluation
- Added new termination criteria to OBBT (max_reduction, max_width, rel_gap/iteration of OBBT) 
- Fixed the issue to tighten only original nonlinear variables (aux vars were counted before)
- `presolve_bt_bound_tol` changed to `1E-4`
- `presolve_bt_obj_bound_tol` added to avoid infeasibility in OBBT iterations

@harshangrjn Please let me know if any new tests are necessary for new OBBT criteria

### CODE REVIEW

**Comment by fatihcengil** [comment]
Issue #181 should be fixed

**Comment by harshangrjn** [comment]
#176 fixed!

**Comment by harshangrjn** [comment]
#133 Doesn't seem like an issue. Added a unit test for expr dereferencing of `@NLexpression`.

**Comment by harshangrjn** [comment]
#108 fixed! Lower bounds do not cross and Alpine terminates with OBBT converging to a global opt.

**Pull request merged**
