### PR TITLE
bound bug fix

### PR DESCRIPTION
**Pull request by harshangrjn**
bug fix on big M bounds

### CODE REVIEW

**Comment by ccoffrin** [comment]
I am a little concerned about this change.  It is not clear that `m.largebound` is sufficiently large not to remove any feasible solution on any problem.  In general it's hard to compute such values quickly.  I would leave it to the user to define reasonable bounds of their model variables based on their domain knowledge and just throw a clear error if some variable is unbounded.

**Comment by harshangrjn** [comment]
@ccoffrin Agreed and we thought about it. Infact, ```m.largebound``` itself can be modified as an user-specified parameter. But we do throw a warning saying the bounds have been altered and can potentially affect the global solutions. The reason we kept this value was because we haven't seen any test instance so far in MINLPLib2 whose variables have such large bounds but certainly we can't discount the fact that one such instance can exist.

**Comment by kaarthiksundar** [comment]
@ccoffrin Is it too much to ask the user to provide finite bounds on every variable in the problem?

**Comment by ccoffrin** [comment]
@kaarthiksundar, I don't think so.  That is what I would recomend, force the user to give inputs that we can currently support.  Just make sure the error message is informative.

**Comment by kaarthiksundar** [comment]
@ccoffrin Okay, I will do that in the MOI wrapper, which I have almost figured out and started in a branch. When it comes to tests, I will need your help. Will keep you updated.

**Pull request merged**
