### PR TITLE
WIP: Add support for Xpress as mip_solver.

### PR DESCRIPTION
**Pull request by hellemo**
I had a go at adding support for Xpress.  Xpress requires time limit as integer, with a suggested fix here, but this might not be the best way to fix it. Open for suggestions.

A change in Xpress.jl to make the XpressSolver struct mutable is necessary for this to work, addressed in this PR: https://github.com/JuliaOpt/Xpress.jl/pull/37

### CODE REVIEW

**Comment by harshangrjn** [comment]
@hellemo Since Alpine just got updated to support JuMP v0.21+ and MOI, can you please update this PR relevant to the Alpine v0.2.0. Since I do not have Xpress, if you can ensure it runs fine with the recent version of Xpress.jl, that would be great. Thanks!

**Comment by hellemo** [comment]
Great news!

I updated the PR and as far as I can tell the only thing holding support for Xpress back it that Xpress demands time limit set as integer, addressed in https://github.com/jump-dev/Xpress.jl/pull/99. I successfully ran all the tests with Xpress in place of Cbc locally with that change applied.

Not quite sure why this PR is now ended up so enormous, comparing from my fork only shows the minor changes from current master.

**Comment by harshangrjn** [comment]
@hellemo Thanks for your quick update. The reason this commit looks so big is because it is counting changes of all updates we did for supporting MOI, compared to your original PR which was submitted when Alpine was on the older version. Looks like all the tests are passing too. Would you mind sending this as a separate PR w.r.t the current master/v0.2.0 so that your changes will reflect correctly? In which case, I shall just delete this PR and merge your newer one.

**Comment by hellemo** [comment]
Right. I figured the rebase would take care of that, but nevermind, I'll close thins and start a new one.

**Pull request closed without merging**
